# Generated by Django 5.0 on 2023-12-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('operating_time', models.TextField()),
                ('fee', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('seat_count', models.IntegerField()),
            ],
        ),
    ]
