# Generated by Django 5.0 on 2023-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='can_booked',
            field=models.BooleanField(default=True),
        ),
    ]
