# Generated by Django 4.2.8 on 2023-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=30)),
                ("car_number", models.CharField(max_length=10)),
                ("user_id", models.CharField(max_length=20)),
                ("is_booked", models.BooleanField(default=False)),
            ],
        ),
    ]
